name: Clojure Dependency Checking

on:
  schedule:
    - cron: '0 0 * * 0' # Run weekly on sundays

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Latest Commit
      uses: actions/checkout@v2.4.0

    - name: Check deps
      uses: nnichols/clojure-dependency-update-action@v3
      with:
        github-token: ${{ secrets.github_token }}
        branch: main
        batch: true